# Axonal extent in um [S-T, M-L]
EC:
  default:
    width: [2000.0, 2000.0]
    offset: [0,0]
CA3:
  default:
    width: [2000.0, 2000.0]
    offset: [0,0]
CA2:
  default:
    width: [2000.0, 2000.0]
    offset: [0,0]
DPYR:
  default:
    width: [1000.0, 1000.0]
    offset: [0,0]
SPYR:
  default:
    width: [1000.0, 1000.0]
    offset: [0,0]
PVBC: # soma in layer pyramidale, PV+
  default:
    width: [1185.0, 1042.0]
    offset: [0,0]
AAC: # soma in layer pyramidale, PV+
  default:
    width: [600.0, 850.0] # double check Li et al 1992
    offset: [0,0]
BS: # soma in layer pyramidale, PV+
  default:
    width: [1530.0, 1150.0]
    offset: [0,0]
CCKBC: # soma in pyramidale, CCK+
  default:
    width: [1000.0, 1000.0] # not well known
    offset: [0,0]
SCA: # soma in radiatum, CCK+
  default:
    width: [1000.0, 1000.0] # not well known
    offset: [0,0]
NGFC: # soma in layer LM, NOS, nPY
  default:
    width: [1200.0, 500.0]
    offset: [0,0]
IVY: # soma in layer pyramidale, NOS, nPY
  default:
    width: [1310.0, 750.0]
    offset: [0,0]
OLM: # soma in layer oriens, SOM+
  default:
    width: [840.0, 500.0]
    offset: [0,0]
IS:
  default:
    width: [800.0, 150.0]
    offset: [0,0]

