# Axonal extent in um [S-T, M-L]

DPYR:

SPYR:

PVBC: # soma in layer pyramidale, PV+
  default:
    width: [1185.0, 1042.0]
    offset: [?,?]
AAC: # soma in layer pyramidale, PV+
  default:
    width: [600.0, 850.0] # double check Li et al 1992
    offset: [?,?]
BS: # soma in layer pyramidale, PV+
  default:
    width: [1530.0, 1150.0]
    offset: [?,?]
CCKBC: # soma in pyramidale, CCK+
  default:
    width: [1000.0, 1000.0] # not well known
    offset: [?,?]
SCA: # soma in radiatum, CCK+
  default:
    width: [1000.0, 1000.0] # not well known
    offset: [?,?]
NGFC: # soma in layer LM, NOS, nPY
  default:
    width: [1200.0, 500.0]
    offset: [?,?]
IVY: # soma in layer pyramidale, NOS, nPY
  default:
    width: [1310.0, 750.0]
    offset: [?,?]
OLM: # soma in layer oriens, SOM+
  default:
    width: [840.0, 500.0]
    offset: [?,?]
IS:
  default:
    width: [800.0, 150.0]
    offset: [?,?]

