# Common definitions used in model configuration of CA1 and dentate gyrus network
SWC Types:
  soma:   1
  axon:   2
  basal:  3
  apical: 4
  trunk:  5
  tuft:   6
  ais:    7
  hillock: 8
Synapse Types:
  excitatory:    0
  inhibitory:    1
  modulatory:    2
Synapse Mechanisms:
  AMPA:    0
  GABA_A:  1
  GABA_B:  2
  NMDA:    30
Layers:
  Hilus: 0
  GCL:   1  ## Granule cell
  IML:   2  ## Inner molecular
  MML:   3  ## Middle molecular
  OML:   4  ## Outer molecular
  SO:    5  ## Oriens
  SP:    6  ## Pyramidale
  SL:    7  ## Lucidum
  SR:    8  ## Radiatum
  SLM:   9  ## Lacunosum-moleculare
Populations:
  DPYR:  100
  SPYR:  101
  PVBC:  102
  AAC:   103
  BS:    104
  CCKBC: 105
  IVY:   106
  NGFC:  107
  OLM:   108
  SCA:   109
  IS:    110
  CA3:   111
  CA2:   112
  EC:    113
Input Selectivity Types:
  random: 0
  ripple: 1
