<<<<<<< HEAD:config/Full_Scale_Connetions.yaml
## Information needed: CA2 projetions and strengths, NMDA unit strengths, IS infomration

=======
## Information needed: CA2 projections and strengths, NMDA unit strengths, ..
>>>>>>> 13f6750ed2dbf621cc5567c0c29ed2bc7d221c9e:config/Full_Scale_Connections.yaml

Synapse Mechanisms:
  AMPA: LinExp2Syn  # SatExp2Syn
  NMDA: FacilNMDA
  GABA_A: LinExp2Syn  # SatExp2Syn
  GABA_B: LinExp2Syn  # SatExp2Syn
Synapse Parameter Rules: !include Synapse_Parameter_Rules.yaml
Axon Extent: !include Axon_Extent.yaml
Connection Velocity: !include Connection_Velocity.yaml
Synapses:
  SPYR:
    CA2:
      type: excitatory
      sections: [basal]
      layers: [SO]
      proportions: []
      mechanisms:
        AMPA:
          tau_rise: 
          tau_decay:
          e: 0
          g_unit: 
        NMDA:
          g_unit:

    CA3:
      type: excitatory
      sections: [apical]
      layers: [SR]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau_rise: 0.5
          tau_decay: 3.0
          e: 0
          g_unit: 
        NMDA:
          g_unit: 
    
    EC:
      type: excitatory
      sections: [apical]
      layers: [SLM]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau_rise: 0.5
          tau_decay: 3.0
          e: 0
          g_unit: 
        NMDA:
          g_unit: 

    SPYR:
      type: excitatory
      sections: [basal]
      layers: [SO]
      proportions: []
      mechanisms:
        AMPA:
          tau_rise: 0.1
          tau_decay: 1.5
          e: 0
          g_unit: 
        NMDA:
          g_unit: 
    DPYR:
      type: excitatory
      sections: [basal]
      layers: [SO]
      proportions: []
      mechanisms:
        AMPA:
          tau_rise: 0.1
          tau_decay: 1.5
          e: 0
          g_unit: 
        NMDA:
          g_unit: 
    AAC:
      type: inhibitory
      sections: [ais]
      layers: [SP]
      proportions: [1.0]
      swctype mechanisms:
        ais:
          GABA_A:
            tau_rise: 0.28
            tau_decay: 8.40
            e: -60
            g_unit: 0.001
    PVBC:   
      type: inhibitory
      sections: [soma]
<<<<<<< HEAD:config/Full_Scale_Connetions.yaml
      layers: [Pyramidale]
=======
      layers: [SP]
>>>>>>> 13f6750ed2dbf621cc5567c0c29ed2bc7d221c9e:config/Full_Scale_Connections.yaml
      proportions: [0.82]
      mechanisms:
        GABA_A:
          tau_rise: 0.30
          tau_decay: 6.2
          e: -60
          g_unit: 0.000186
    CCKBC:  
      type: inhibitory
      sections: [soma, apical]
      layers: [SP, SP]
      proportions: [0.18, 1.0]
      mechanisms:
        GABA_A:
          tau_rise: 0.2
          tau_decay: 4.20
          e: -60
          g_unit: 0.000450
    BS:   
      type: inhibitory
      sections: [apical]
      layers: [SR]
      proportions: [0.194]
      mechanisms:
        GABA_A:
          tau_rise: 0.1
          tau_decay: 9.7
          e: -60
          g_unit: 0.000510
    IVY:
      type: inhibitory
      sections: [apical]
      layers: [SR]
      proportions: [0.787]
      mechanisms:
        GABA_A:
          tau_rise: 1.1
          tau_decay: 11.0
          e: -60
          g_unit: 0.000077
    SCA:
      type: inhibitory
      sections: [apical]
      layers: [SR]
      proportions: [0.019]
      mechanisms:
        GABA_A:
          tau_rise: 0.15
          tau_decay: 3.9
          e: -60
          g_unit: 0.000850

    NGFC: 
      type: inhibitory
      sections: [apical]
      layers: [SLM]
      proportions: [0.625]
      swctype mechanisms:
        apical:
          GABA_A:
            tau_rise:  9.0
            tau_decay: 39.0
            e:   -60
            g_unit: 0.000145
          GABA_B:
            tau_rise:  180.0
            tau_decay: 200.0
            e:   -90
            g_unit: 0.000145
    OLM: 
      type: inhibitory
      sections: [apical]
      layers: [SLM]
      proportions: [0.375]
      swctype mechanisms:
        apical:
          GABA_A:
            tau_rise:  0.13
            tau_decay: 11.0
            e:   -60
            g_unit: 0.00120

  DPYR:
    CA2:
      type: excitatory
      sections: [basal]
      layers: [SO]
      proportions: []
      mechanisms:
        AMPA:
          tau_rise: 
          tau_decay:
          e: 0
          g_unit: 
        NMDA:
          g_unit:

    CA3:
      type: excitatory
      sections: [apical]
      layers: [SR]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau_rise: 0.5
          tau_decay: 3.0
          e: 0
          g_unit: 
        NMDA:
          g_unit: 
    
    EC:
      type: excitatory
      sections: [apical]
      layers: [SLM]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau_rise: 0.5
          tau_decay: 3.0
          e: 0
          g_unit: 
        NMDA:
          g_unit: 

    SPYR:
      type: excitatory
      sections: [basal]
      layers: [SO]
      proportions: []
      mechanisms:
        AMPA:
          tau_rise: 0.1
          tau_decay: 1.5
          e: 0
          g_unit: 
        NMDA:
          g_unit: 
    DPYR:
      type: excitatory
      sections: [basal]
      layers: [SO]
      proportions: []
      mechanisms:
        AMPA:
          tau_rise: 0.1
          tau_decay: 1.5
          e: 0
          g_unit: 
        NMDA:
          g_unit: 
    AAC:
      type: inhibitory
      sections: [ais]
      layers: [SP]
      proportions: [1.0]
      swctype mechanisms:
        ais:
          GABA_A:
            tau_rise: 0.28
            tau_decay: 8.40
            e: -60
            g_unit: 0.001
    PVBC:   
      type: inhibitory
      sections: [soma]
<<<<<<< HEAD:config/Full_Scale_Connetions.yaml
      layers: [Pyramidale]
=======
      layers: [SP]
>>>>>>> 13f6750ed2dbf621cc5567c0c29ed2bc7d221c9e:config/Full_Scale_Connections.yaml
      proportions: [0.82]
      mechanisms:
        GABA_A:
          tau_rise: 0.30
          tau_decay: 6.2
          e: -60
          g_unit: 0.000372
    CCKBC:  
      type: inhibitory
      sections: [soma, apical]
      layers: [SP, SP]
      proportions: [0.18, 1.0]
      mechanisms:
        GABA_A:
          tau_rise: 0.2
          tau_decay: 4.20
          e: -60
          g_unit: 0.000450
    BS:   
      type: inhibitory
      sections: [apical]
      layers: [SR]
      proportions: [0.194]
      mechanisms:
        GABA_A:
          tau_rise: 0.1
          tau_decay: 9.7
          e: -60
          g_unit: 0.000510
    IVY:
      type: inhibitory
      sections: [apical]
      layers: [SR]
      proportions: [0.787]
      mechanisms:
        GABA_A:
          tau_rise: 1.1
          tau_decay: 11.0
          e: -60
          g_unit: 0.000077
    SCA:
      type: inhibitory
      sections: [apical]
      layers: [SR]
      proportions: [0.019]
      mechanisms:
        GABA_A:
          tau_rise: 0.15
          tau_decay: 3.9
          e: -60
          g_unit: 0.000850

    NGFC: 
      type: inhibitory
      sections: [apical]
      layers: [SLM]
      proportions: [0.625]
      swctype mechanisms:
        apical:
          GABA_A:
            tau_rise:  9.0
            tau_decay: 39.0
            e:   -60
            g_unit: 0.000145
          GABA_B:
            tau_rise:  180.0
            tau_decay: 200.0
            e:   -90
            g_unit: 0.000145
    OLM: 
      type: inhibitory
      sections: [apical]
      layers: [SLM]
      proportions: [0.375]
      swctype mechanisms:
        apical:
          GABA_A:
            tau_rise:  0.13
            tau_decay: 11.0
            e:   -60
            g_unit: 0.00120


  PVBC:
    CA2:
      type: excitatory
      sections: []
      layers: []
      proportions: []
      mechanisms:
        AMPA:
          tau_rise: 
          tau_decay:
          e: 0
          g_unit: 
    CA3:
      type: excitatory
      sections: [apical]
      layers: [Radiatum]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau_rise: 2.0
          tau_decay: 6.3
          e: 0
          g_unit: 
    EC:
      type: excitatory
      sections: [apical]
      layers: [LM]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau_rise: 2.0
          tau_decay: 6.3
          e: 0
          g_unit:      
    SPYR:
      type: excitatory
      sections: []
      layers: []
      proportions: []
      mechanisms:
        AMPA:
          tau_rise: 0.07
          tau_decay: 0.20
          e: 0
          g_unit: 
        NMDA:
          g_unit: 
    DPYR:
      type: excitatory
      sections: []
      layers: []
      proportions: []
      mechanisms:
        AMPA:
          tau_rise: 0.07
          tau_decay: 0.20
          e: 0
          g_unit: 
        NMDA:
          g_unit: 
    PVBC:   
      type: inhibitory
      sections: [soma, apical]
      layers: [Pyramidale, Pyramidale]
      proportions: [0.16, 0.16]
      mechanisms:
        GABA_A:
          tau_rise: 0.08
          tau_decay: 4.8
          e: -60
          g_unit:
    CCKBC:  
      type: inhibitory
      sections: [soma, apical]
      layers: [Pyramidale, Pyramidale]
      proportions: [0.84, 0.84]
      mechanisms:
        GABA_A:
          tau_rise: 0.432
          tau_decay: 4.9
          e: -60
          g_unit: 
    BS:   
      type: inhibitory
      sections: [apical]
      layers: [Radiatum]
      proportions: [0.21]
      mechanisms:
        GABA_A:
          tau_rise: 0.287
          tau_decay: 2.67
          e: -60
          g_unit: 
    Ivy:
      type: inhibitory
      sections: [apical]
      layers: [Radiatum]
      proportions: [0.76]
      mechanisms:
        GABA_A:
          tau_rise: 2.9
          tau_decay: 3.1
          e: -60
          g_unit: 
    SCA:
      type: inhibitory
      sections: [apical]
      layers: [Radiatum]
      proportions: [0.03]
      mechanisms:
        GABA_A:
          tau_rise: 0.419
          tau_decay: 4.99
          e: -60
          g_unit: 

    NGFC: 
      type: inhibitory
      sections: [apical]
      layers: [LM]
      proportions: [0.595]
      swctype mechanisms:
        apical:
          GABA_A:
            tau_rise:  8.0
            tau_decay: 39.0
            e:   -60
            g_unit: 
          GABA_B:
            tau_rise:  180.0
            tau_decay: 200.0
            e:   -90
            g_unit: 
    OLM: 
      type: inhibitory
      sections: [apical]
      layers: [LM]
      proportions: [0.405]
      swctype mechanisms:
        apical:
          GABA_A:
            tau_rise:  0.25
            tau_decay: 7.5
            e:   -60
            g_unit: 
            
            g_unit: 
    IS: 
      type: inhibitory
      sections: []
      layers: []
      proportions: []
      swctype mechanisms:
        apical:
          GABA_A:
            tau_rise:  
            tau_decay:
            e:   -60
            g_unit: 
            
            

