## Information needed: CA2 projetions and strengths needed, NMDA unit strengths, IS infomration

Synapse Mechanisms:
  AMPA: LinExp2Syn  # SatExp2Syn
  NMDA: FacilNMDA
  GABA_A: LinExp2Syn  # SatExp2Syn
  GABA_B: LinExp2Syn  # SatExp2Syn
Synapse Parameter Rules: !include Synapse_Parameter_Rules.yaml
Axon Extent: !include Axon_Extent.yaml
Connection Velocity: !include Connection_Velocity.yaml
Synapses:
  SPYR:
    CA2:
      type: excitatory
      sections: [basal]
      layers: [SO]
      proportions: [0.47]
      mechanisms:
        AMPA:
          tau_rise: 0.5
          tau_decay: 3.0
          e: 0
          g_unit: 0.0001
        NMDA:
          g_unit:

    CA3:
      type: excitatory
      sections: [basal, apical]
      layers: [SO, SR]
      proportions: [0.54, 1.0]
      mechanisms:
        AMPA:
          tau_rise: 0.5
          tau_decay: 3.0
          e: 0
          g_unit: 0.0001
        NMDA:
          g_unit: 
    
    EC:
      type: excitatory
      sections: [apical]
      layers: [SLM]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau_rise: 0.5
          tau_decay: 3.0
          e: 0
          g_unit: 0.00015
        NMDA:
          g_unit: 

    SPYR:
      type: excitatory
      sections: [basal]
      layers: [SO]
      proportions: [0.015]
      mechanisms:
        AMPA:
          tau_rise: 0.1
          tau_decay: 1.5
          e: 0
          g_unit: 0.000405
        NMDA:
          g_unit: 
    DPYR:
      type: excitatory
      sections: [basal]
      layers: [SO]
      proportions: [0.015]
      mechanisms:
        AMPA:
          tau_rise: 0.1
          tau_decay: 1.5
          e: 0
          g_unit: 0.000405
        NMDA:
          g_unit: 
    AAC:
      type: inhibitory
      sections: [ais]
      layers: [SP]
      proportions: [1.0]
      swctype mechanisms:
        ais:
          GABA_A:
            tau_rise: 0.28
            tau_decay: 8.40
            e: -60
            g_unit: 0.001
    PVBC:   
      type: inhibitory
      sections: [soma, basal, apical]
      layers: [SP, SO, SR]
      proportions: [0.65, 0.17, 0.15]
      mechanisms:
        GABA_A:
          tau_rise: 0.30
          tau_decay: 6.2
          e: -60
          g_unit: 0.000186
    CCKBC:  
      type: inhibitory
      sections: [soma, basal, apical]
      layers: [SP, SO, SR]
      proportions: [0.35, 0.112, 0.09]
      mechanisms:
        GABA_A:
          tau_rise: 0.2
          tau_decay: 4.20
          e: -60
          g_unit: 0.000450
    BS:   
      type: inhibitory
      sections: [basal, apical]
      layers: [SO, SR]
      proportions: [0.18, 0.12]
      mechanisms:
        GABA_A:
          tau_rise: 0.1
          tau_decay: 9.7
          e: -60
          g_unit: 0.000510
    IVY:
      type: inhibitory
      sections: [basal, apical, apical]
      layers: [SO, SR, SLM]
      proportions: [0.52, 0.54, 0.15]
      mechanisms:
        GABA_A:
          tau_rise: 1.1
          tau_decay: 11.0
          e: -60
          g_unit: 0.000077
    SCA:
      type: inhibitory
      sections: [basal, apical, apical]
      layers: [SO, SR, SLM]
      proportions: [0.003, 0.03, 0.005]
      mechanisms:
        GABA_A:
          tau_rise: 0.15
          tau_decay: 3.9
          e: -60
          g_unit: 0.000850

    NGFC: 
      type: inhibitory
      sections: [apical, apical]
      layers: [SR, SLM]
      proportions: [0.07, 0.52]
      swctype mechanisms:
        apical:
          GABA_A:
            tau_rise:  9.0
            tau_decay: 39.0
            e:   -60
            g_unit: 0.000145
          GABA_B:
            tau_rise:  180.0
            tau_decay: 200.0
            e:   -90
            g_unit: 0.000145
    OLM: 
      type: inhibitory
      sections: [basal,  apical]
      layers: [SO, SLM]
      proportions: [0.015, 0.32]
      swctype mechanisms:
        apical:
          GABA_A:
            tau_rise:  0.13
            tau_decay: 11.0
            e:   -60
            g_unit: 0.00120

  DPYR:
     CA2:
      type: excitatory
      sections: [basal]
      layers: [SO]
      proportions: [0.47]
      mechanisms:
        AMPA:
          tau_rise: 0.5
          tau_decay: 3.0
          e: 0
          g_unit: 0.0003
        NMDA:
          g_unit:

    CA3:
      type: excitatory
      sections: [basal, apical]
      layers: [SO, SR]
      proportions: [0.54, 1.0]
      mechanisms:
        AMPA:
          tau_rise: 0.5
          tau_decay: 3.0
          e: 0
          g_unit: 0.0001
        NMDA:
          g_unit: 
    
    EC:
      type: excitatory
      sections: [apical]
      layers: [SLM]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau_rise: 0.5
          tau_decay: 3.0
          e: 0
          g_unit: 0.000105
        NMDA:
          g_unit: 

    SPYR:
      type: excitatory
      sections: [basal]
      layers: [SO]
      proportions: [0.015]
      mechanisms:
        AMPA:
          tau_rise: 0.1
          tau_decay: 1.5
          e: 0
          g_unit: 0.000405
        NMDA:
          g_unit: 
    DPYR:
      type: excitatory
      sections: [basal]
      layers: [SO]
      proportions: [0.015]
      mechanisms:
        AMPA:
          tau_rise: 0.1
          tau_decay: 1.5
          e: 0
          g_unit: 0.000405
        NMDA:
          g_unit: 
    AAC:
      type: inhibitory
      sections: [ais]
      layers: [SP]
      proportions: [1.0]
      swctype mechanisms:
        ais:
          GABA_A:
            tau_rise: 0.28
            tau_decay: 8.40
            e: -60
            g_unit: 0.001
    PVBC:   
      type: inhibitory
      sections: [soma, basal, apical]
      layers: [SP, SO, SR]
      proportions: [0.65, 0.17, 0.15]
      mechanisms:
        GABA_A:
          tau_rise: 0.30
          tau_decay: 6.2
          e: -60
          g_unit: 0.000372
    CCKBC:  
      type: inhibitory
      sections: [soma, basal, apical]
      layers: [SP, SO, SR]
      proportions: [0.35, 0.112, 0.09]
      mechanisms:
        GABA_A:
          tau_rise: 0.2
          tau_decay: 4.20
          e: -60
          g_unit: 0.000450
    BS:   
      type: inhibitory
      sections: [basal, apical]
      layers: [SO, SR]
      proportions: [0.18, 0.12]
      mechanisms:
        GABA_A:
          tau_rise: 0.1
          tau_decay: 9.7
          e: -60
          g_unit: 0.000510
    IVY:
      type: inhibitory
      sections: [basal, apical, apical]
      layers: [SO, SR, SLM]
      proportions: [0.52, 0.54, 0.15]
      mechanisms:
        GABA_A:
          tau_rise: 1.1
          tau_decay: 11.0
          e: -60
          g_unit: 0.000077
    SCA:
      type: inhibitory
      sections: [basal, apical, apical]
      layers: [SO, SR, SLM]
      proportions: [0.003, 0.03, 0.005]
      mechanisms:
        GABA_A:
          tau_rise: 0.15
          tau_decay: 3.9
          e: -60
          g_unit: 0.000850

    NGFC: 
      type: inhibitory
      sections: [apical, apical]
      layers: [SR, SLM]
      proportions: [0.07, 0.52]
      swctype mechanisms:
        apical:
          GABA_A:
            tau_rise:  9.0
            tau_decay: 39.0
            e:   -60
            g_unit: 0.000145
          GABA_B:
            tau_rise:  180.0
            tau_decay: 200.0
            e:   -90
            g_unit: 0.000145
    OLM: 
      type: inhibitory
      sections: [basal,  apical]
      layers: [SO, SLM]
      proportions: [0.015, 0.32]
      swctype mechanisms:
        apical:
          GABA_A:
            tau_rise:  0.13
            tau_decay: 11.0
            e:   -60
            g_unit: 0.00120

  # need exc, weights
  PVBC:
    CA2:
      type: excitatory
      sections: []
      layers: []
      proportions: []
      mechanisms:
        AMPA:
          tau_rise: 
          tau_decay:
          e: 0
          g_unit: 
    CA3:
      type: excitatory
      sections: [apical]
      layers: [SR]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau_rise: 2.0
          tau_decay: 6.3
          e: 0
          g_unit: 
    EC:
      type: excitatory
      sections: [apical]
      layers: [SLM]
      proportions: [1.0]
      mechanisms:
        AMPA:
          tau_rise: 2.0
          tau_decay: 6.3
          e: 0
          g_unit:      
    SPYR:
      type: excitatory
      sections: []
      layers: []
      proportions: []
      mechanisms:
        AMPA:
          tau_rise: 0.07
          tau_decay: 0.20
          e: 0
          g_unit: 
        NMDA:
          g_unit: 
    DPYR:
      type: excitatory
      sections: []
      layers: []
      proportions: []
      mechanisms:
        AMPA:
          tau_rise: 0.07
          tau_decay: 0.20
          e: 0
          g_unit: 
        NMDA:
          g_unit: 
    PVBC:   
      type: inhibitory
      sections: [soma]
      layers: [SP]
      proportions: [0.40]
      mechanisms:
        GABA_A:
          tau_rise: 0.08
          tau_decay: 4.8
          e: -60
          g_unit:
    CCKBC:  
      type: inhibitory
      sections: [soma, basal, apical, apical]
      layers: [SP, SO, SR, SLM]
      proportions: [0.60, 0.434, 0.22, 0.11]
      mechanisms:
        GABA_A:
          tau_rise: 0.432
          tau_decay: 4.9
          e: -60
          g_unit: 
    BS:   
      type: inhibitory
      sections: [basal, apical, apical]
      layers: [SO, SP, SR]
      proportions: [0.386, 0.39, 0.1]
      mechanisms:
        GABA_A:
          tau_rise: 0.287
          tau_decay: 2.67
          e: -60
          g_unit: 
    IVY:
      type: inhibitory
      sections: [basal, apical, apica, apical]
      layers: [SO, SP, SR, SLM]
      proportions: [0.17, 0.58, 0.62, 0.29]
      mechanisms:
        GABA_A:
          tau_rise: 2.9
          tau_decay: 3.1
          e: -60
          g_unit: 
    SCA:
      type: inhibitory
      sections: [basal, apical, apical]
      layers: [SO, SP, SR]
      proportions: [0.01, 0.03, 0.03]
      mechanisms:
        GABA_A:
          tau_rise: 0.419
          tau_decay: 4.99
          e: -60
          g_unit: 

    NGFC: 
      type: inhibitory
      sections: [apical, apical]
      layers: [SR, SLM]
      proportions: [0.03, 0.33]
      swctype mechanisms:
        apical:
          GABA_A:
            tau_rise:  8.0
            tau_decay: 39.0
            e:   -60
            g_unit: 
          GABA_B:
            tau_rise:  180.0
            tau_decay: 200.0
            e:   -90
            g_unit: 
    OLM: 
      type: inhibitory
      sections: [apical]
      layers: [SLM]
      proportions: [0.270]
      swctype mechanisms:
        apical:
          GABA_A:
            tau_rise:  0.25
            tau_decay: 7.5
            e:   -60
            g_unit: 
            
    
  # need exc, weights
  BS:
    CA2:
      type: excitatory
      sections: []
      layers: []
      proportions: []
      mechanisms:
        AMPA:
          tau_rise: 
          tau_decay:
          e: 0
          g_unit: 
    CA3:
      type: excitatory
      sections: []
      layers: []
      proportions: []
      mechanisms:
        AMPA:
          tau_rise: 
          tau_decay: 
          e: 0
          g_unit: 
    EC:
      type: excitatory
      sections: []
      layers: []
      proportions: []
      mechanisms:
        AMPA:
          tau_rise: 
          tau_decay: 
          e: 0
          g_unit:      
    SPYR:
      type: excitatory
      sections: []
      layers: []
      proportions: []
      mechanisms:
        AMPA:
          tau_rise: 
          tau_decay: 
          e: 0
          g_unit: 
        NMDA:
          g_unit: 
    DPYR:
      type: excitatory
      sections: []
      layers: []
      proportions: []
      mechanisms:
        AMPA:
          tau_rise: 
          tau_decay: 
          e: 0
          g_unit: 
        NMDA:
          g_unit: 
    PVBC:   
      type: inhibitory
      sections: [soma]
      layers: [SP]
      proportions: [0.33]
      mechanisms:
        GABA_A:
          tau_rise: 0.180
          tau_decay: 0.45
          e: -60
          g_unit:
    CCKBC:  
      type: inhibitory
      sections: [soma, basal, apical, apical]
      layers: [SP, SO, SR, SLM]
      proportions: [0.67, 0.51, 0.30, 0.12]
      mechanisms:
        GABA_A:
          tau_rise: 0.432
          tau_decay: 4.9
          e: -60
          g_unit: 
    BS:   
      type: inhibitory
      sections: [basal, apical, apical]
      layers: [SO, SP, SR]
      proportions: [0.28, 0.35, 0.08]
      mechanisms:
        GABA_A:
          tau_rise: 0.287
          tau_decay: 2.67
          e: -60
          g_unit: 
    IVY:
      type: inhibitory
      sections: [basal, apical, apical, apical]
      layers: [SO, SP, SR, SLM]
      proportions: [0.12, 0.59, 0.54, 0.18]
      mechanisms:
        GABA_A:
          tau_rise: 2.9
          tau_decay: 3.1
          e: -60
          g_unit: 
    SCA:
      type: inhibitory
      sections: [basal, apical, apical]
      layers: [SO, SP, SR]
      proportions: [0.02, 0.06, 0.04]
      mechanisms:
        GABA_A:
          tau_rise: 0.419
          tau_decay: 4.99
          e: -60
          g_unit: 

    NGFC: 
      type: inhibitory
      sections: [apical, apical]
      layers: [SR, SLM]
      proportions: [0.04, 0.37]
      swctype mechanisms:
        apical:
          GABA_A:
            tau_rise:  8.0
            tau_decay: 39.0
            e:   -60
            g_unit: 
          GABA_B:
            tau_rise:  180.0
            tau_decay: 200.0
            e:   -90
            g_unit: 
    OLM: 
      type: inhibitory
      sections: [apical]
      layers: [SLM]
      proportions: [0.33]
      swctype mechanisms:
        apical:
          GABA_A:
            tau_rise:  0.60
            tau_decay: 15.0
            e:   -60
            g_unit:          
    IS: 
      type: inhibitory
      sections: [apical]
      layers: [SO]
      proportions: [0.07]
      swctype mechanisms:
        apical:
          GABA_A:
            tau_rise:  1.1
            tau_decay: 
            e:   -60
            g_unit: 
            
              
            
  # need exc, weights
  CCKBC:
    CA2:
      type: excitatory
      sections: []
      layers: []
      proportions: []
      mechanisms:
        AMPA:
          tau_rise: 
          tau_decay:
          e: 0
          g_unit: 
    CA3:
      type: excitatory
      sections: []
      layers: []
      proportions: []
      mechanisms:
        AMPA:
          tau_rise: 
          tau_decay: 
          e: 0
          g_unit: 
    EC:
      type: excitatory
      sections: []
      layers: []
      proportions: []
      mechanisms:
        AMPA:
          tau_rise: 
          tau_decay: 
          e: 0
          g_unit:      
    SPYR:
      type: excitatory
      sections: []
      layers: []
      proportions: []
      mechanisms:
        AMPA:
          tau_rise: 
          tau_decay: 
          e: 0
          g_unit: 
        NMDA:
          g_unit: 
    DPYR:
      type: excitatory
      sections: []
      layers: []
      proportions: []
      mechanisms:
        AMPA:
          tau_rise: 
          tau_decay: 
          e: 0
          g_unit: 
        NMDA:
          g_unit: 
    PVBC:   
      type: inhibitory
      sections: [soma]
      layers: [SP]
      proportions: [0.35]
      mechanisms:
        GABA_A:
          tau_rise: 0.287
          tau_decay: 2.67
          e: -60
          g_unit:
    CCKBC:  
      type: inhibitory
      sections: [soma, basal, apical, apical]
      layers: [SP, SO, SR, SLM]
      proportions: [0.65, 0.28, 0.12, 0.04]
      mechanisms:
        GABA_A:
          tau_rise: 0.432
          tau_decay: 4.9
          e: -60
          g_unit: 
    BS:   
      type: inhibitory
      sections: [basal, apical, apical]
      layers: [SO, SP, SR]
      proportions: [0.45, 0.35, 0.09]
      mechanisms:
        GABA_A:
          tau_rise: 0.287
          tau_decay: 2.67
          e: -60
          g_unit: 
    IVY:
      type: inhibitory
      sections: [basal, apical, apical, apical]
      layers: [SO, SP, SR, SLM]
      proportions: [0.23, 0.60, 0.70, 0.22]
      mechanisms:
        GABA_A:
          tau_rise: 2.9
          tau_decay: 3.1
          e: -60
          g_unit: 
    SCA:
      type: inhibitory
      sections: [basal, apical, apical]
      layers: [SO, SP, SR]
      proportions: [0.02, 0.05, 0.04]
      mechanisms:
        GABA_A:
          tau_rise: 0.419
          tau_decay: 4.99
          e: -60
          g_unit: 

    NGFC: 
      type: inhibitory
      sections: [apical, apical]
      layers: [SR, SLM]
      proportions: [0.05, 0.40]
      swctype mechanisms:
        apical:
          GABA_A:
            tau_rise:  8.0
            tau_decay: 39.0
            e:   -60
            g_unit: 
          GABA_B:
            tau_rise:  180.0
            tau_decay: 200.0
            e:   -90
            g_unit: 
    OLM: 
      type: inhibitory
      sections: [apical]
      layers: [SLM]
      proportions: [0.34]
      swctype mechanisms:
        apical:
          GABA_A:
            tau_rise:  0.72
            tau_decay: 20.20
            e:   -60
            g_unit: 
            
    IS: 
      type: inhibitory
      sections: [apical]
      layers: [SO]
      proportions: [0.02]
      swctype mechanisms:
        apical:
          GABA_A:
            tau_rise:  1.1
            tau_decay: 
            e:   -60
            g_unit: 