Parametric Surface:
  Origin:
    U: median
    V: median
    L: max
  Layer Extents:
    SO:  [[0.0,0.0,0.0], [4000.0,1250.0,100.0]]
    SP:  [[0.0,0.0,100.0],[4000.0,1250.0,150.0]]
    SR:  [[0.0,0.0,150.0], [4000.0,1250.0,350.0]]
    SLM: [[0.0, 0.0,350.0], [4000.0, 1250.0, 450.0]]
  Rotation: [0.0, 0.0, 0.0]
Cell Distribution:
  DPYR:
    SO:  0
    SP:  155750
    SR:  0
    SLM: 0
  SPYR:
    SO:  0
    SP:  155750
    SR:  0
    SLM: 0
  PVBC:
    SO:  1320
    SP:  3880
    SR:  330
    SLM: 0
  AAC:
    SO:  350
    SP:  1030
    SR:  0
    SLM: 0
  BS:
    SO:  530
    SP:  1550 
    SR:  130
    SLM: 0
  CCKBC:
    SO:  780
    SP:  940
    SR:  1170
    SLM: 710
  IVY:
    SO:  980
    SP:  5410
    SR:  2420
    SLM: 0
  NGFC:
    SO:  0
    SP:  0
    SR:  610
    SLM: 2970
  OLM:
    SO:  1640
    SP:  0
    SR:  0
    SLM: 0
  SCA:
    SO:  0
    SP:  0
    SR:  400
    SLM: 0
  IS:
    SO:  780
    SP:  2710
    SR:  1000
    SLM: 1010
  CA3:
    SO:  0
    SP:  0
    SR:  204700
    SLM: 0
  CA2:
    SO:  40000
    SP:  0
    SR:  0
    SLM: 0
  EC:
    SO:  0
    SP:  0
    SR:  0
    SLM: 250000
