Parametric Surface:
  Origin:
    U: median
    V: median
    L: max
  Layer Extents:
    Oriens:     [[0.0,0.0,0.0], [4000.0,1250.0,100.0]]
    Pyramidale: [[0.0,0.0,100.0],[4000.0,1250.0,150.0]]
    Radiatum:   [[0.0,0.0,150.0], [4000.0,1250.0,350.0]]
    LM:         [[0.0, 0.0,350.0], [4000.0, 1250.0, 450.0]]
  Rotation: [0.0, 0.0, 0.0]
Cell Distribution:
  DPYR:
    Oriens:     0
    Pyramidale: 155750
    Radiatum:   0
    LM:         0
  SPYR:
    Oriens:     0
    Pyramidale: 155750
    Radiatum:   0
    LM:         0
  PVBC:
    Oriens:     1320
    Pyramidale: 3880
    Radiatum:   330
    LM:         0
  AAC:
    Oriens:     350
    Pyramidale: 1030
    Radiatum:   0
    LM:         0
  BS:
    Oriens:     530
    Pyramidale: 1550 
    Radiatum:   130
    LM:         0
  CCKBC:
    Oriens:     780
    Pyramidale: 940
    Radiatum:   1170
    LM:         710
  IVY:
    Oriens:     980
    Pyramidale: 5410
    Radiatum:   2420
    LM:         0
  NGFC:
    Oriens:     0
    Pyramidale: 0
    Radiatum:   610
    LM:         2970
  OLM:
    Oriens:     1640
    Pyramidale: 0
    Radiatum:   0
    LM:         0
  SCA:
    Oriens:     0
    Pyramidale: 0
    Radiatum:   400
    LM:         0
  IS:
    Oriens: 780
    Pyramidale:  2710
    Radiatum:  1000
    LM: 1010
  CA3:
    Oriens:     0
    Pyramidale: 0
    Radiatum:   204700
    LM:         0
  CA2:
    Oriens: 40000
    Pyramidale: 0
    Radiatum: 0
    LM: 0
  EC:
    Oriens:     0
    Pyramidale: 0
    Radiatum:   0
    LM:         250000
