## Schafer Collateral Associated synapse density configuration

## https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6782984/
## Calbindin
## Flip apical with basal orientation?


apical:
  excitatory:
    Radiatum:
      mean: 0.94
      variance: 0.1
    LM:
      mean: 0.75
      variance: 0.1
  inhibitory:
    Radiatum:
      mean: 0.18
      variance: 0.1
    LM:
      mean: 0.16
      variance: 0.1
      
basal:
  excitatory:
    Oriens:
      mean: 0.61
      variance: 0.1

  inhibitory:
    Oriens:
      mean: 0.20
      variance: 0.1
soma:
  inhibitory:
    default:
      mean: 0.12
      variance: 0.1
  excitatory:
    default:
      mean: 0.14
      variance: 0.1
