## Ivy cell synapse density configuration
# Number of excitatory and inhibitory connections obtained from conndata_211.data
# dendritic length estimated from https://pubmed.ncbi.nlm.nih.gov/18367092/ of 1260 microns


apical:
  excitatory:
    Radiatum:
      mean: 3.16
      variance: 0.1
    LM:
      mean: 3.16
      variance: 0.1
  inhibitory:
    Radiatum:
      mean: 0.60
      variance: 0.10
    LM:
      mean: 0.60
      variance: 0.10
      
basal:
  excitatory:
    Oriens:
      mean: 3.16
      variance: 0.1
  inhibitory:
    Oriens:
      mean: 0.60
      variance: 0.1
