## Ivy cell synapse density configuration
# Number of excitatory and inhibitory connections obtained from conndata_403.data
# dendrities length equal to width of oriens + width of radiatum multiplied by a factor of 20
# assumed synapses distributed evenly across layers



apical:
  excitatory:
    Radiatum:
      mean: 0.64
      variance: 0.1
  inhibitory:
    Radiatum:
      mean: 0.06
      variance: 0.1
      
basal:
  excitatory:
    Oriens:
      mean: 0.64
      variance: 0.1

  inhibitory:
    Oriens:
      mean: 0.06
      variance: 0.1
