## NGFC cell synapse density configuration
# number of connections obtained from conndata_403.data
# total dendritic length equal to width of radiatum and width of LM multipled by a factor of 20n
# assumed synapses distributed evenly across layers



apical:
  excitatory:
    LM:
      mean: 0.175
      variance: 0.1
    Radiatum:
       mean: 0.175
       variance: 0.1
  inhibitory:
    LM:
      mean: 0.07
      variance: 0.1
    Radiatum:
      mean: 0.07
      variance: 0.1
      
