## NGFC cell synapse density configuration
# number of connections obtained from conndata_211.dat
# dendrite length assumped to be 1000 um https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2230758/


apical:
  excitatory:
    SR:
       mean: 1.04
       variance: 0.1
  inhibitory:
    SR:
      mean: 0.89
      variance: 0.1
      

basal:
  excitatory:
    SLM:
      mean: 1.04
      variance: 0.1
  inhibitory:
    SLM:
      mean: 0.89
      variance: 0.01
