## OLM cell synapse density configuration
# number of inhibitory and excitatory connections from conndata_403.data
# total dendritic length of 2000 um estimated from https://onlinelibrary.wiley.com/doi/full/10.1111/ejn.14549
# Assumed synapses distributed evenly across layers

apical:
  excitatory:
    Oriens:
      mean: 3.57
      variance: 0.1
  inhibitory:
    Oriens:
      mean: 0.961
      variance: 0.1
      
