## Schafer Collateral Associated synapse density configuration

## https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6782984/
## Calbindin


apical:
  excitatory:
    SO:
      mean: 0.55
      variance: 0.1
  inhibitory:
    SO:
      mean: 0.38
      variance: 0.1
      
basal:
  excitatory:
    SR:
      mean: 0.75
      variance: 0.1
    SLM:
      mean: 0.75
      variance: 0.1

  inhibitory:
    SR:
      mean: 0.28
      variance: 0.1
    SLM:
      mean: 0.75
      variance: 0.1
soma:
  inhibitory:
    default:
      mean: 0.18
      variance: 0.1
  excitatory:
    default:
      mean: 0.13
      variance: 0.1
